import type { Metadata } from 'next';
import MainHeader from '@/components/layout/header/main-header';
import MainFooter from '@/components/layout/footer/main-footer';
import React from 'react';

export const metadata: Metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <MainHeader />
      <main>{children}</main>
      <MainFooter isPrivate={false} />
    </>
  );
}
